# Generated by Django 4.1.1 on 2022-11-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=100),
        ),
    ]
